### ISSUE TITLE
Using this template for thesis in english

### ISSUE THREAD

**Issue by MetalGanon** [SCD-Aix-Marseille-Universite/latexamu#35]
Hello,

Thank you for this template. However, I'm struggling to convert it in english.

I tried to replace the line:
\RequirePackage[english, main=french]{babel}
by:
\RequirePackage[main=english, french]{babel}
but it did not change anything.

I tried removing the french option but the compilation crash. 

How can I convert the template to have "Table des matières" to become "Table of contents"?

Thank you.

**Comment by mlincett** [comment]
Hi @MetalGanon , indeed the current structure is misleading. Check `tex/abstract.tex` for `\selectlanguage` directives, as by default whatever comes after the abstract file will be set to French. If you are writing a thesis in English you should use `main=english`, remove move the `\selectlanguage` directives from the `tex/abstract.tex` file and use them to set your introduction in French.

Probably this kind of directives should be moved to the main `these.tex` file, so that at a glance the user can know where the environment is changed.

**Comment by eurruby** [comment]
I'll take a look at this. See also for siunitx :
https://github.com/SCD-Aix-Marseille-Universite/latexamu/issues/29

**Comment by eurruby** [comment]
I have made the changes as recommended by @mlincett. Thank you again!
@MetalGanon You should use \RequirePackage[french, main=english]{babel} instead of \RequirePackage[main=english, french]{babel}
